# Configuration for Alacritty, the GPU enhanced terminal emulator.
# alt_send_esc: false
background_opacity: 1.0
live_config_reload: true

shell:
  program: /bin/zsh

window:
  position: { x: 0, y: 0 }
  padding:  { x: 2, y: 2 }
  dynamic_padding: false
  dynamic_title: true
  decorations: buttonless
  startup_mode: SimpleFullscreen
  #startup_mode: Windowed

#scrolling:
  #history: 10000
  #multiplier: 3

font:
  size: 11.5
  #size: 16.5
  normal:
    family: MesloLGS NF
    style: Regular

key_bindings:
  #- { key: 26,          mods: Alt,        chars: "|"    }
  #- { key: 26,          mods: Alt|Shift,  chars: "\\"   }
  #- { key: Apostrophe,  mods: Alt,        chars: "'"    }
  #- { key: Return,                        chars: "\x0d" }
  #- { key: Space,       mods: Control,    chars: "\x00" }
  #- { key: LBracket,    mods: Alt,        chars: "["    }
  #- { key: RBracket,    mods: Alt,        chars: "]"    }
  #- { key: LBracket,    mods: Alt|Shift,  chars: "{"    }
  #- { key: RBracket,    mods: Alt|Shift,  chars: "}"    }
  - { key: Minus,       mods: Shift|Command,            action: IncreaseFontSize }
  - { key: N,           mods: Alt|Shift|Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }

bell:
  duration: 0

cursor:
  vi_mode_style: None
  unfocused_hollow: true

# https://github.com/alacritty/alacritty/wiki/Color-schemes#gruvbox
# Colors (Gruvbox dark)
colors:
  primary:
    background:        &gruvbox_dark_bg '#1d2021'
    foreground:        &normal_foreground '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text:   CellBackground
    cursor: CellForeground
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   *gruvbox_dark_bg
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   *normal_foreground
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'
