export ANSIBLE_NOCOWS=1
export BROWSER=google-chrome
export EDITOR=vim
export FZF_CTRL_T_COMMAND='fd --type f'
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS='--height 30 --reverse'
export GPG_TTY=$(tty)
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LESS="XFR";
export LS_COLORS=
export SSH_KEY_PATH="~/.ssh/id_rsa"
export TT_HOURS_PER_DAY=6
