#!/bin/bash

export HOMEBREW_PREFIX; HOMEBREW_PREFIX="$(/opt/homebrew/bin/brew --prefix 2>/dev/null)";

export ANSIBLE_NOCOWS="1";
export AUTO_REMOVE_SLASH="0";
export DOTFILES_HOME; DOTFILES_HOME="$(dirname "$(dirname "$(dirname "$(readlink "${BASH_SOURCE[0]}")")")")";
export FZF_DEFAULT_COMMAND="fd --type f";
export FZF_DEFAULT_OPTS="--height 10 --reverse";
export HISTSIZE="10000";
export LANG="en_US.UTF-8";
export LESS="XFR";
export LS_COLORS="";
export SSLMAKER_HOME="/opt/homebrew/etc/sslmaker";
export TT_HOURS_PER_MONTH="150";

export SHELL_NAME="zsh";
[ -n "$BASH_VERSION" ] && SHELL_NAME="bash";

[ -n "$SSH_TTY" ] && export SNIPCLIP_HOSTNAME="127.0.0.1";
export SNIPCLIP_PORT="38888"

command -v xcode-select >/dev/null && PATH="$(xcode-select --print-path)/usr/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/gettext/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/ncurses/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/openssl/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/sqlite/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/go/libexec/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/python/libexec/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/ruby/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/opt/perl/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/bin:$PATH";
[ -n "$HOMEBREW_PREFIX" ] && PATH="$HOMEBREW_PREFIX/sbin:$PATH";
command -v cargo >/dev/null && PATH="$HOME/.cargo/bin:$PATH";
[ -n "$DOTFILES_HOME" ] && PATH="$DOTFILES_HOME/bin:$PATH";
PATH="$(perl -e'print join ":",grep{!$u{$_}++&&-e&&length}split ":",$ENV{PATH}')";
export PATH;

[ -z "$VIM_BIN" ] && VIM_BIN="$(command -v nvim)";
[ -z "$VIM_BIN" ] && VIM_BIN="$(command -v vim)";
[ -z "$VIM_BIN" ] && VIM_BIN="$(command -v vi)";
export VIM_BIN;
export EDITOR="$VIM_BIN";
export DOTFILES_BASHRC_WAS_LOADED=1;
