# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

umask 0002
# setopt ignore_eof # disable ^D
setopt notify
unsetopt extendedglob # Allow "git show HEAD^"

for ZSH_SOURCE in $(find $HOME/.config/zsh -maxdepth 1 | grep '/zsh/[0-9]\+-' | sort); do
  export ZSH_SOURCE;
  source $ZSH_SOURCE;
  unset ZSH_SOURCE;
done
