call plug#begin('~/.vim/plugged')

if has("nvim")
  Plug 'ibhagwan/nvim-fzf'
  Plug 'ibhagwan/fzf-lua'
else
  Plug 'junegunn/fzf'
endif

Plug 'skywind3000/asyncrun.vim'
Plug 'itchyny/lightline.vim'
Plug 'gruvbox-community/gruvbox'
Plug 'andis-sprinkis/lightline-gruvbox-dark.vim'

" helpers
Plug 'conradirwin/vim-bracketed-paste'
Plug 'terryma/vim-multiple-cursors'

" syntax
Plug 'ap/vim-css-color'
Plug 'cakebaker/scss-syntax.vim'
Plug 'evanleck/vim-svelte'
Plug 'gabrielelana/vim-markdown'
Plug 'hail2u/vim-css3-syntax'
Plug 'mattn/emmet-vim'
Plug 'othree/html5.vim'
Plug 'pangloss/vim-javascript'
Plug 'posva/vim-vue'
Plug 'vim-perl/vim-perl'
Plug 'yko/mojo.vim'

if has("nvim")
  Plug 'neovim/nvim-lspconfig'
  Plug 'hrsh7th/nvim-compe'
endif

call plug#end()

set autoindent
set autoread
set backspace=indent,eol,start
set complete=.,w,b,u,t,kspell
set completeopt=menuone,noinsert,noselect
set encoding=utf-8
set expandtab
set history=100
set incsearch
set laststatus=2
set mouse=i
set nobackup
set nocompatible
set nofoldenable
set nohlsearch
set noshowmode
set nostartofline
set noswapfile
set nowrap
set nowritebackup
set number
set relativenumber
set scrolloff=8
set shell=zsh
set shiftround
set shiftwidth=2
set showcmd
set signcolumn=yes
set smartcase
set smartindent
set softtabstop=2
set statusline=%f\ %{strlen(&fenc)?&fenc:'none'},%{&ff},%{&ft}\ (%B)\ %h%m%r%=%c,%l/%L\ %P"
set tabstop=8
set wildignore+=*/.git/*,*/node_modules/*,*/.DS_Store,*/vendor,*.min.*,*.png,*.jpg
set wildignorecase
set wildmode=list:longest

" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 0
let g:netrw_fastbrowse = 1
let g:netrw_winsize = 25
let g:netrw_altv = 1

" Misc config
source ~/.vim/include/ft.vim
source ~/.vim/include/keymap.vim
source ~/.vim/include/colors.vim
source ~/.vim/include/fzf.vim

" Utilities
source ~/.vim/include/lastpos.vim
source ~/.vim/include/mkdir.vim
source ~/.vim/include/spelling.vim

" Vim plugins
source ~/.vim/include/emmet.vim
source ~/.vim/include/multiple-cursors.vim

if has("nvim")
  lua require'lsp'
endif
