[ -z "$XDG_CACHE_HOME" ] && XDG_CACHE_HOME="$HOME/.cache";
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config";
[ -z "$HOMEBREW_CELLAR" ] && HOMEBREW_CELLAR="/opt/homebrew/Cellar";
[ -z "$HOMEBREW_PREFIX" ] && HOMEBREW_PREFIX="/opt/homebrew";
[ -z "$HOMEBREW_REPOSITORY" ] && HOMEBREW_REPOSITORY="/opt/homebrew";

[ -d "$HOME/.config/zsh/completion" ] && fpath=("$HOME/.config/zsh/completion" $fpath);
[ -d "$HOMEBREW_PREFIX/share/zsh/site-functions" ] && fpath=("$HOMEBREW_PREFIX/share/zsh/site-functions" $fpath);
[ -d "$HOMEBREW_PREFIX/share/zsh-completions" ] && fpath=("$HOMEBREW_PREFIX/share/zsh-completions" $fpath);

# Lines configured by zsh-newuser-install
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

umask 0002
setopt notify
unsetopt extendedglob # Allow "git show HEAD^"

readlink_f() {
  [ "x$UNAME" = "xDarwin" ] && readlink $* || readlink -f $*;
}

ZSH_CONFIG_HOME="$(readlink_f $XDG_CONFIG_HOME/zsh)";
for ZSH_SOURCE in $(find $ZSH_CONFIG_HOME -maxdepth 1 | grep 'zsh/[0-9]\+-' | sort); do
  export ZSH_SOURCE="$(readlink_f $ZSH_SOURCE)";
  source $ZSH_SOURCE;
  unset ZSH_SOURCE;
done

command -v starship >/dev/null && eval "$(starship init zsh)";
